apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-site
spec:
  selector:
    matchLabels:
      app: django-site
  template:
    metadata:
      labels:
        app: django-site
    spec:
      containers:
      - name: django-site
        image: 5013979855192531/django-utm:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
